max_num_nodes = 2**(8)
q = 0.2
p = (1-q)/2
jumps= 5
min_active_nodes = 10
num_runs = 1
num_iters = int(5e3)
split = 0.9
length_of_trial = 150
feature_vec_length = length_of_trial+2
curr_state = str(int(max_num_nodes/2))
ID_bits = 8